###############################################################################
# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weather-control-ui
  labels:
    app: weather-control-ui
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-control-ui
      serving: "true"
  template:
    metadata:
      labels:
        app: weather-control-ui
        version: latest
        serving: "true"
        visualize: "true"
      annotations:
        visualizer/uses: weather-control-service,weather-data-service,redis
    spec:
      containers:
      - name: weather-control-ui
        image: saturnism/weather-control-ui:latest
        args:
        - --weather-data.endpoint=http://weather-data-service:8080/weather
        - --weather-control.endpoint=http://weather-control-service:8080/api/weatherControlLogs
        - --redis.endpoint=tcp://redis:6379
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        ports:
        - name: http
          containerPort: 8080
